/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 19 02:14:07 GMT 2018
 */

package com.uepb.tcc.yatzy.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.uepb.tcc.yatzy.Yatzy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Yatzy_ESTest extends Yatzy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int int0 = Yatzy.amplaSequencia(5, 5, 5, 5, 5);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.pequenaSequencia(1, 1, (-674), 0, 120);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -675
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.pequenaSequencia(1, 2589, 2589, 0, 931);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2588
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.dois_pares(4, 1, 4, 2707, 4);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2706
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = Yatzy.dois(0, 0, 0, 6, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.pequenaSequencia(1, 1, 1, 3, (-14));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -15
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = Yatzy.um(6, 12, 6, (-1341), 12);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = Yatzy.dois(1312, 1312, 1526, (-3151), 2166);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = Yatzy.chance(1, 0, 2705, 1, 0);
      assertEquals(2707, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = Yatzy.chance(20, (-4767), (-4767), (-4767), 20);
      assertEquals((-14261), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.yatzy((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.tres_de_um_tipo(1, 1, 1, 5, 50);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 49
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy(0, (-503), 0, 0, 0);
      int[] intArray0 = new int[4];
      yatzy0.dados = intArray0;
      yatzy0.dados = null;
      // Undeclared exception!
      try { 
        yatzy0.seis();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.quatro_de_um_tipo(1, 15, 139, 12, (-2068));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 14
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy((-1625), (-1625), (-1625), 0, 1532);
      int[] intArray0 = new int[5];
      yatzy0.dados = intArray0;
      yatzy0.dados = null;
      // Undeclared exception!
      try { 
        yatzy0.quatro();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy(2, 2, (-1), 2, 0);
      int[] intArray0 = new int[3];
      yatzy0.dados = intArray0;
      // Undeclared exception!
      try { 
        yatzy0.quatro();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.pontuacao_par(1365, 394, (-4884), (-1), (-4159));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1364
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.pequenaSequencia(0, 0, 0, 0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.dois_pares(4, 0, 6, 4, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy((-2004), (-2004), (-1), (-1), (-1));
      yatzy0.dados = null;
      // Undeclared exception!
      try { 
        yatzy0.cinco();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      // Undeclared exception!
      try { 
        Yatzy.amplaSequencia(1, 1, 1, 1225, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1224
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      int int0 = Yatzy.casaCheia(1, 1, 6, 6, 1);
      assertEquals(15, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      int int0 = Yatzy.casaCheia(1, 6, 6, 6, 4);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int int0 = Yatzy.casaCheia(1, 4, 6, 6, 1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int int0 = Yatzy.tres_de_um_tipo(1, 1, 1, 1, 1);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      int int0 = Yatzy.quatro_de_um_tipo(6, 6, 6, 6, 6);
      assertEquals(24, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      int int0 = Yatzy.dois_pares(4, 4, 1, 4, 4);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      int int0 = Yatzy.pontuacao_par(1, 1, 1, 1, 1);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int int0 = Yatzy.pontuacao_par(6, 6, 6, 6, 6);
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy(6, 12, 1, 12, 12);
      int int0 = yatzy0.seis();
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy((-1), 1191, 5, 14601, 5);
      int int0 = yatzy0.cinco();
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy(4, 0, 1, 0, 1);
      int int0 = yatzy0.cinco();
      assertEquals(0, int0);
      assertEquals(4, yatzy0.quatro());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy(4, (-653), (-6647), (-1), 1592);
      int int0 = yatzy0.quatro();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy((-1625), (-1625), (-1625), 0, 1532);
      int int0 = yatzy0.quatro();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      int int0 = Yatzy.tres(0, 0, 0, (-1954), 3);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      int int0 = Yatzy.tres((-4495), (-879), 1, 3, (-1));
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int int0 = Yatzy.tres(0, (-775), 3, (-1726), 0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      int int0 = Yatzy.tres(0, 3, 0, (-39), 7);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      int int0 = Yatzy.tres(3, 1, 312, 0, 1615);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      int int0 = Yatzy.tres(1347, 2781, 6, 2781, 2781);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      int int0 = Yatzy.dois(1961, 2436, 2, (-1455), 2436);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      int int0 = Yatzy.dois(2, 2, 0, 0, 2);
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      int int0 = Yatzy.dois((-4122), 50, (-39), 2, 1);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      int int0 = Yatzy.um(1, 2, 1, (-1341), 2);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      int int0 = Yatzy.um(1, 1, 1, 1, 1);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy((-804), 1, 1, 50, 1412);
      int[] intArray0 = new int[7];
      intArray0[0] = 1;
      intArray0[1] = 1;
      intArray0[2] = 1;
      intArray0[3] = 2;
      intArray0[4] = 2;
      intArray0[5] = 1;
      intArray0[6] = 1;
      yatzy0.dados = intArray0;
      int int0 = Yatzy.yatzy(yatzy0.dados);
      assertEquals(50, int0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = 1;
      intArray0[1] = 1;
      intArray0[2] = 1;
      intArray0[3] = 1;
      intArray0[4] = 1;
      intArray0[5] = 1;
      intArray0[6] = 5;
      int int0 = Yatzy.yatzy(intArray0);
      assertArrayEquals(new int[] {1, 1, 1, 1, 1, 1, 5}, intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      int[] intArray0 = new int[7];
      // Undeclared exception!
      try { 
        Yatzy.yatzy(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.uepb.tcc.yatzy.Yatzy", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      int int0 = Yatzy.chance(0, 0, 0, 0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Yatzy yatzy0 = new Yatzy(1, 1, (-2073), (-2512), 28);
      int int0 = yatzy0.seis();
      assertEquals(0, int0);
  }
}
